"""
The table of public names renamed to PEP 8 snake_case for Lightweaver 1.0.

This is the single source of truth for the deprecation shims in
`lightweaver.deprecation`, the `lightweaver.migrate` tool, and the tests. The old
names keep working (with a `LightweaverDeprecationWarning`), and will be removed
in a future release.

Naming rule: ordinary camelCase words become snake_case; physics symbols keep
their case (`dJ`, `J`, `B`, `Q`), except element symbols, which are lowercase
(`nh_tot`, `h_pops`); names that are only an N-count or a symbol (`Nspace`,
`Aji`) are unchanged, and N-counts with a trailing word keep the N glued to the
first word (`Nlambda_gen`).
"""

RENAMES: dict[str, str] = {
    # Context / iteration entry points
    'eqPops': 'eq_pops',
    'conserveCharge': 'conserve_charge',
    'ngOptions': 'ng_options',
    'initSol': 'init_sol',
    'nrHOnly': 'nr_h_only',
    'detailedAtomPrd': 'detailed_atom_prd',
    'crswCallback': 'crsw_callback',
    'crswDone': 'crsw_done',
    'backgroundProvider': 'background_provider',
    'formalSolver': 'formal_solver',
    'interpFn': 'interp_fn',
    'fsIterScheme': 'fs_iter_scheme',
    'activeAtoms': 'active_atoms',
    'detailedAtoms': 'detailed_atoms',
    'depthData': 'depth_data',
    'extraParams': 'extra_params',
    'chunkSize': 'chunk_size',
    'fixCollisionalRates': 'fix_collisional_rates',
    'lambdaIterate': 'lambda_iterate',
    'updateJ': 'update_J',
    'prevTimePops': 'prev_time_pops',
    'updateBcs': 'update_bcs',
    'upOnly': 'up_only',
    'refinePrd': 'refine_prd',
    'returnCtx': 'return_ctx',
    'ngUpdate': 'ng_update',
    'hOnly': 'h_only',
    'fdCollisionRates': 'fd_collision_rates',
    'timeDependentData': 'time_dependent_data',
    'NmaxIter': 'max_iter',
    'maxIter': 'max_iter',
    'JTol': 'J_tol',
    'popsTol': 'pops_tol',
    'rhoTol': 'rho_tol',
    'prdIterTol': 'prd_iter_tol',
    'maxPrdSubIter': 'max_prd_sub_iter',
    'printInterval': 'print_interval',
    'returnFinalConvergence': 'return_final_convergence',
    'JUpdate': 'J_update',
    'popsUpdate': 'pops_update',
    'prdUpdate': 'prd_update',
    'popsOnly': 'pops_only',
    'preserveProfiles': 'preserve_profiles',
    'prevState': 'prev_state',
    'prevSpect': 'prev_spect',
    'fillDiagonal': 'fill_diagonal',
    # IterationUpdate / NgOptions
    'dJMax': 'dJ_max',
    'dJMaxIdx': 'dJ_max_idx',
    'dJPrdMax': 'dJ_prd_max',
    'dJPrdMaxIdx': 'dJ_prd_max_idx',
    'dNeMax': 'dne_max',
    'dNeMaxIdx': 'dne_max_idx',
    'dPops': 'dpops',
    'dPopsMax': 'dpops_max',
    'dPopsMaxIdx': 'dpops_max_idx',
    'dRho': 'drho',
    'dRhoMax': 'drho_max',
    'dRhoMaxIdx': 'drho_max_idx',
    'updatedJ': 'updated_J',
    'updatedJPrd': 'updated_J_prd',
    'updatedNe': 'updated_ne',
    'updatedPops': 'updated_pops',
    'updatedRho': 'updated_rho',
    'ngAccelerated': 'ng_accelerated',
    'NprdSubIter': 'Nprd_sub_iter',
    'lowerThreshold': 'lower_threshold',
    # Atmosphere / Layout / Stratifications / LwAtmosphere
    'nHTot': 'nh_tot',
    'hydrogenPops': 'hydrogen_pops',
    'vlosMu': 'vlos_mu',
    'gammaB': 'gamma_B',
    'chiB': 'chi_B',
    'cosGamma': 'cos_gamma',
    'depthScale': 'depth_scale',
    'convertScales': 'convert_scales',
    'tauRef': 'tau_ref',
    'logG': 'log_g',
    'PeTop': 'Pe_top',
    'lowerBc': 'lower_bc',
    'upperBc': 'upper_bc',
    'xLowerBc': 'x_lower_bc',
    'xUpperBc': 'x_upper_bc',
    'yLowerBc': 'y_lower_bc',
    'yUpperBc': 'y_upper_bc',
    'zLowerBc': 'z_lower_bc',
    'zUpperBc': 'z_upper_bc',
    'indexVector': 'index_vector',
    'pyAtmos': 'py_atmos',
    # Atomic models
    'qCore': 'q_core',
    'qWing': 'q_wing',
    'vMicroChar': 'v_micro_char',
    'deltaLambda': 'delta_lambda',
    'wavelengthGrid': 'wavelength_grid',
    'alphaGrid': 'alpha_grid',
    'minWavelength': 'min_wavelength',
    'NlambdaGen': 'Nlambda_gen',
    'gLandeEff': 'g_lande_eff',
    'reproduceOldRHBug': 'reproduce_old_RH_bug',
    'electronExp': 'electron_exp',
    'hydrogenExp': 'hydrogen_exp',
    'temperatureExp': 'temperature_exp',
    'iLevel': 'i_level',
    'jLevel': 'j_level',
    'transId': 'trans_id',
    'lambdaEdge': 'lambda_edge',
    'minLambda': 'min_lambda',
    'overlyingContinuumLevel': 'overlying_continuum_level',
    'lsCoupling': 'LS_coupling',
    'vBroad': 'v_broad',
    'vRel35H': 'v_rel_35_h',
    'vRel35He': 'v_rel_35_he',
    'cStark23': 'c_stark_23',
    'barklemVals': 'barklem_vals',
    # Atom/transition views (LwAtom, LwTransition, LwSpectrum, LwDepthData)
    'nStar': 'n_star',
    'nTotal': 'n_total',
    'aDamp': 'a_damp',
    'phiQ': 'phi_Q',
    'phiU': 'phi_U',
    'phiV': 'phi_V',
    'psiQ': 'psi_Q',
    'psiU': 'psi_U',
    'psiV': 'psi_V',
    'rhoPrd': 'rho_prd',
    'toObs': 'to_obs',
    'atomicModel': 'atomic_model',
    'modelPops': 'model_pops',
    'transModel': 'trans_model',
    'fsIterSchemeProperties': 'fs_iter_scheme_properties',
    'inConstructor': 'in_constructor',
    # RadiativeSet / SpeciesStateTable / SpectrumConfiguration / abundances
    'radSet': 'rad_set',
    'atomicPops': 'atomic_pops',
    'molecularPops': 'molecular_pops',
    'molecularTable': 'molecular_table',
    'HminPops': 'hmin_pops',
    'hPops': 'h_pops',
    'radiativeRates': 'radiative_rates',
    'nlteStartingPops': 'nlte_starting_pops',
    'passiveAtoms': 'passive_atoms',
    'activeSet': 'active_set',
    'passiveSet': 'passive_set',
    'detailedStaticSet': 'detailed_static_set',
    'extraWavelengths': 'extra_wavelengths',
    'lambdaReference': 'lambda_reference',
    'activeTrans': 'active_trans',
    'activeWavelengths': 'active_wavelengths',
    'transWavelengths': 'trans_wavelengths',
    'blueIdx': 'blue_idx',
    'redIdx': 'red_idx',
    'NprdTrans': 'Nprd_trans',
    'updateTotals': 'update_totals',
    'computeDiff': 'compute_diff',
    'prevNeRatio': 'prev_ne_ratio',
    'sortedAtoms': 'sorted_atoms',
    'atomicAbundance': 'atomic_abundance',
    'abundanceData': 'abundance_data',
    'abundDex': 'abund_dex',
    'avgMass': 'avg_mass',
    'massPerH': 'mass_per_h',
    'totalAbundance': 'total_abundance',
    'isotopeProportions': 'isotope_proportions',
    'kuruczPfPath': 'kurucz_pf_path',
    'ionPot': 'ion_pot',
    'update_nTotal': 'update_n_total',
    'update_lte_atoms_Hmin_pops': 'update_lte_atoms_hmin_pops',
    'massData': 'mass_data',
    'nameMapping': 'name_mapping',
    # Molecules, backgrounds, utilities, config, benchmark
    'filePath': 'file_path',
    'tempRange': 'temp_range',
    'formationTempRange': 'formation_temp_range',
    'eqcCoeffs': 'eqc_coeffs',
    'pfCoeffs': 'pf_coeffs',
    'elementCount': 'element_count',
    'chiIn': 'chi_in',
    'etaIn': 'eta_in',
    'scaIn': 'sca_in',
    'initVal': 'init_val',
    'nEff': 'n_eff',
    'specInt': 'spec_int',
    'outUnits': 'out_units',
    'extendGridNm': 'extend_grid_nm',
    'configPath': 'config_path',
    'implLibs': 'impl_libs',
    'warmUp': 'warm_up',
    'writeConfig': 'write_config',
}

# Renamed keys of the `time_dependent_data` dict passed to `Context.nr_post_update`
# (old keys are still accepted, with a warning).
NR_DICT_KEY_RENAMES: dict[str, str] = {
    'nPrev': 'n_prev',
}

# Renamed without a deprecated alias: parameters that are only passed internally
# (fsIterSchemeProperties, inConstructor: Context -> LwAtom; computeDiff: the
# lte_pops_impl numba kernel), or positionally to a cpdef hook that Cython can't
# wrap (chiIn, etaIn, scaIn: BackgroundProvider.compute_background).
INTERNAL_NO_ALIAS: frozenset[str] = frozenset(
    {'fsIterSchemeProperties', 'inConstructor', 'computeDiff', 'chiIn', 'etaIn', 'scaIn'}
)
