name: LwTest
channels:
  - default
  - conda-forge
dependencies:
  - python==3.8
  - pip
  - pip:
    - numpy
    - scipy
    - matplotlib
    - astropy
    - numba
    - parse
    - jupyterlab
    - cython
    - specutils
    - tqdm
    - weno4
