name: Lightweaver
channels:
  - default
  - conda-forge
dependencies:
  - python>=3.8
  - pip
  - pip:
    - numpy<1.22,>=1.18
    - scipy
    - matplotlib
    - astropy
    - numba>=0.55
    - parse
    - jupyterlab
    - cython
    - specutils
    - tqdm
    - weno4
