[build-system]
requires = ['setuptools>=42', 'wheel', 'setuptools_scm[toml]>=3.4', 'cython', 'numpy==1.20.3']
build-backend = 'setuptools.build_meta'

[tool.setuptools_scm]
write_to = 'lightweaver/version.py'