[build-system]
requires = ['setuptools>=45,<60', 'wheel', 'setuptools_scm[toml]>=3.4', 'cython', 'numpy>=1.19']
build-backend = 'setuptools.build_meta'

[tool.setuptools_scm]
write_to = 'lightweaver/version.py'
