name: BuildWheels

runs-on:
  workflow_dispatch:
  release:
    types:
    - published

jobs:
  build_sdist:
    name: Build SDist
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - run: python -m pip install pep517
    - run: python -m pep517.build --source .

    - uses: actions/upload-artifact@v2
      with:
        path: dist/*.tar.gz
